### ISSUE TITLE
Travis build?

### ISSUE THREAD

**Issue by mj1618** [cadc/glue-stack#17]
Hey man if you'd like a travis build just put this in `.travis.yml` and create an account

```
matrix:
  include:
    - language: java
      before_install:
        - cd api
      install: true
      script: mvn clean install
    - language: node_js
      node_js: "6"
      before_install:
        - cd ui
notifications:
  email: false
```
